# Generated by Django 3.1.3 on 2021-01-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64, verbose_name='book name')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='add time')),
            ],
        ),
    ]
